name: Continuous integration
on: [push]
jobs:
  buildAndTest:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "pnpm"
      - name: pnpm install, build
        run: |
          pnpm install
          pnpm build
      - run: tree
